version: '3'
services:
  php:
    build: .
    ports: 
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password
      MYSQL_DATABASE: mysql-database
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - "8000:80"
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-password
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
volumes:
    persistent: